import { ActivityItem, SupervisorProfile } from '../types';
import { createActivityPlaceholderSvg } from './imageUtils';

export const INITIAL_SUPERVISOR_PROFILE: SupervisorProfile = {
  name: 'ARIYANTI, M.Pd',
  nip: '19821216 200903 2 007',
  role: 'Pengawas Sekolah',
  signingTitle: 'Pengawas/Pendamping Sekolah,',
  city: 'Lumajang',
  signingDate: '30 September 2026',
  periodMonth: 'SEPTEMBER 2026',
  institutionGov: 'PEMERINTAH PROVINSI JAWA TIMUR',
  institutionDept: 'DINAS PENDIDIKAN PROVINSI JAWA TIMUR',
  institutionBranch: 'CABANG DINAS PENDIDIKAN WILAYAH JEMBER',
  institutionAddress: 'Jl. Kalimantan No. 42 / 0331-4355870 Email : cabangdispendikjember@yahoo.com',
  institutionPostal: 'Jember 68124',
  institutionEmail: 'cabangdispendikjember@yahoo.com',
  institutionPhone: '0331-4355870',
  driveFolders: {
    kolaboratif: 'https://drive.google.com/drive/folders/1TL5pRoQ7QLeRwD5kYJQeWdK5Yo7c4VQe?usp=sharing',
    berorientasi_pelayanan: 'https://drive.google.com/drive/folders/1TL5pRoQ7QLeRwD5kYJQeWdK5Yo7c4VQe?usp=sharing',
    akuntabel: 'https://drive.google.com/drive/folders/1TL5pRoQ7QLeRwD5kYJQeWdK5Yo7c4VQe?usp=sharing',
    kompeten: 'https://drive.google.com/drive/folders/1TL5pRoQ7QLeRwD5kYJQeWdK5Yo7c4VQe?usp=sharing',
    harmonis: 'https://drive.google.com/drive/folders/1TL5pRoQ7QLeRwD5kYJQeWdK5Yo7c4VQe?usp=sharing',
    loyal: 'https://drive.google.com/drive/folders/1TL5pRoQ7QLeRwD5kYJQeWdK5Yo7c4VQe?usp=sharing',
    adaptif: 'https://drive.google.com/drive/folders/1TL5pRoQ7QLeRwD5kYJQeWdK5Yo7c4VQe?usp=sharing',
  },
  selfAssessments: {
    kolaboratif:
      'Saya responsif terhadap informasi dari pimpinan dan Korwas/MKPS, responsif dengan sekolah binaan/dampingan, selalu menjaga sinergitas dan kerjasama dengan rekan sejawat, Korwas, MKPS dan Sekolah Binaan/Dampingan.',
    berorientasi_pelayanan:
      'Saya berkomitmen memberikan pelayanan prima demi kepuasan pemangku kepentingan pendidikan, mendampingi kepala sekolah dan guru binaan dengan ramah, cekatan, solutif, serta terus melakukan perbaikan tiada henti.',
    akuntabel:
      'Saya melaksanakan tugas pengawasan dengan penuh integritas, jujur, bertanggung jawab, cermat, disiplin, berintegritas tinggi, serta menggunakan sarana dan waktu kedinasan secara efektif dan efisien.',
    kompeten:
      'Saya terus belajar dan mengembangkan kapabilitas diri, memfasilitasi peningkatan kompetensi guru dan kepala sekolah binaan, serta melaksanakan tugas kepengawasan dengan kualitas terbaik.',
    harmonis:
      'Saya senantiasa membangun lingkungan kerja dan pembinaan yang kondusif, menghargai setiap insan pendidikan apapun latar belakangnya, serta suka menolong rekan sejawat dan warga sekolah binaan.',
    loyal:
      'Saya memegang teguh ideologi Pancasila, UUD 1945, setia kepada NKRI dan Pemerintah yang sah, menjaga nama baik Korps ASN pengawas sekolah, serta menjaga kerahasiaan jabatan dan dinas.',
    adaptif:
      'Saya cepat beradaptasi menghadapi dinamika perubahan pendidikan, antusias mengimplementasikan platform digital pembelajaran terbaru, dan proaktif mendampingi transformasi sekolah binaan.',
  },
};

export const INITIAL_ACTIVITIES: ActivityItem[] = [
  {
    id: 'act-1',
    date: '2026-09-02',
    dateFormatted: 'Rabu, 2 September 2026',
    name: 'Mengikuti senam Bersama di Cabdin Wil. Jember_Kab. Lumajang',
    location: 'Cabang Dinas Pendidikan Wil Jember-Kab Lumajang',
    participants: '• Pengawas\n• Staf Cabdin',
    results:
      'Kegiatan Senam berjalan lancar Bersama dengan pengawas dan pegawai Cabdin Wil. Jember-Kab. Lumajang Bersama dengan SMKN 1 Tekung',
    photoUrl: createActivityPlaceholderSvg('Senam Bersama Cabdin Jember-Lumajang', '02/09/2026'),
    driveUrl: 'https://drive.google.com/drive/folders/1TL5pRoQ7QLeRwD5kYJQeWdK5Yo7c4VQe?usp=sharing',
    categories: ['kolaboratif', 'harmonis'],
    createdAt: '2026-09-02T08:00:00Z',
  },
  {
    id: 'act-2',
    date: '2026-09-02',
    dateFormatted: 'Rabu, 2 September 2026',
    name: 'Mengikuti sosialisasi RSDM bersama Cabdindik Wilayah Jember',
    location: 'SMAN 2 Lumajang',
    participants: '• Kasubag Cabdin\n• Kasi SMA/SMK\n• Pengawas\n• Kepala Sekolah',
    results: 'Aplikasi RSDM tersampaikan dengan baik, sebagai dasar distribusi ASN',
    photoUrl: createActivityPlaceholderSvg('Sosialisasi RSDM SMAN 2 Lumajang', '02/09/2026'),
    driveUrl: 'https://drive.google.com/drive/folders/1TL5pRoQ7QLeRwD5kYJQeWdK5Yo7c4VQe?usp=sharing',
    categories: ['kolaboratif', 'kompeten', 'adaptif'],
    createdAt: '2026-09-02T10:30:00Z',
  },
  {
    id: 'act-3',
    date: '2026-09-03',
    dateFormatted: 'Kamis, 3 September 2026',
    name: 'Mengikuti Rapat Koordinasi TKA Jatim',
    location: 'Zoom Meeting',
    participants: '• Kepala Dinas Pendidikan Prov Jatim\n• Pengawas Sekolah',
    results: 'Tahapan dalam TKA dapat dilaksanakan dengan baik',
    photoUrl: createActivityPlaceholderSvg('Rakor TKA Jatim Daring', '03/09/2026'),
    driveUrl: '',
    categories: ['kolaboratif', 'akuntabel', 'kompeten'],
    createdAt: '2026-09-03T09:00:00Z',
  },
  {
    id: 'act-4',
    date: '2026-09-07',
    dateFormatted: 'Senin, 7 September 2026',
    name: 'Rakorprov APSI Jawa Timur',
    location: 'Aula BBPMP Surabaya',
    participants: '• Kepala Dinas Pendidikan Prov Jatim\n• Pengawas Sekolah\n• Pengurus APSI',
    results:
      'Sinergi Pengawas Sekolah Jawa Timur: Optimalisasi Pemantauan, Penilaian, dan Pembinaan menuju Peningkatan Budaya Mutu di Sekolah Binaan',
    photoUrl: createActivityPlaceholderSvg('Rakorprov APSI Aula BBPMP', '07/09/2026'),
    driveUrl: 'https://drive.google.com/drive/folders/1TL5pRoQ7QLeRwD5kYJQeWdK5Yo7c4VQe?usp=sharing',
    categories: ['kolaboratif', 'kompeten', 'berorientasi_pelayanan'],
    createdAt: '2026-09-07T08:30:00Z',
  },
  {
    id: 'act-5',
    date: '2026-09-09',
    dateFormatted: 'Rabu, 9 September 2026',
    name: 'Mengikuti senam Bersama di Cabdin Wil. Jember_Kab. Lumajang',
    location: 'Cabang Dinas Pendidikan Wil Jember-Kab Lumajang',
    participants: '• Pengawas\n• Staf Cabdin',
    results:
      'Kegiatan Senam berjalan lancar Bersama dengan pengawas dan pegawai Cabdin Wil. Jember-Kab. Lumajang Bersama dengan SMK PGRI Lumajang',
    photoUrl: createActivityPlaceholderSvg('Senam Sehat SMK PGRI Lumajang', '09/09/2026'),
    driveUrl: '',
    categories: ['kolaboratif', 'harmonis'],
    createdAt: '2026-09-09T07:30:00Z',
  },
  {
    id: 'act-6',
    date: '2026-09-14',
    dateFormatted: 'Senin, 14 September 2026',
    name: 'Apel Senin Pagi',
    location: 'Kantor Cabang Dinas Wilayah Jember-Kab. Lumajang',
    participants: '• Pengawas Sekolah\n• Staf Cabdin Wilayah Jember',
    results:
      'Terjadi peningkatan disiplin dan kedisiplinan, membangun kebersamaan dan kekeluargaan antar pegawai, serta menjadi sarana komunikasi efektif untuk penyampaian arahan pimpinan, informasi penting, dan evaluasi kinerja.',
    photoUrl: createActivityPlaceholderSvg('Apel Senin Pagi Cabdin Jember', '14/09/2026'),
    driveUrl: 'https://drive.google.com/drive/folders/1TL5pRoQ7QLeRwD5kYJQeWdK5Yo7c4VQe?usp=sharing',
    categories: ['kolaboratif', 'loyal', 'akuntabel'],
    createdAt: '2026-09-14T07:15:00Z',
  },
  {
    id: 'act-7',
    date: '2026-09-14',
    dateFormatted: 'Senin, 14 September 2026',
    name: 'Mengikuti Sosialisasi Gempita 2026',
    location: 'Zoom Meeting',
    participants: '• Kepala Dinas Pendidikan Prov Jatim\n• Kabid GTK\n• Pengawas\n• Kepala Sekolah',
    results: 'Juknis dan Prosedur pengumpulan karya Gempita 2026 tersampaikan dengan baik',
    photoUrl: createActivityPlaceholderSvg('Sosialisasi Gempita 2026 Zoom', '14/09/2026'),
    driveUrl: '',
    categories: ['kolaboratif', 'kompeten', 'adaptif'],
    createdAt: '2026-09-14T13:00:00Z',
  },
  {
    id: 'act-8',
    date: '2026-09-15',
    dateFormatted: 'Selasa, 15 September 2026',
    name: 'Mengikuti sosialisasi Jatim Learning Digital Vault (JDLV)',
    location: 'Zoom Meeting',
    participants: '• Kepala Dinas Pendidikan Prov Jatim\n• Kabid TIKP\n• Pengawas\n• Kepala Sekolah',
    results: 'Aplikasi Jatim Learning Digital Vault (JDLV) tersosialisasikan dengan baik',
    photoUrl: createActivityPlaceholderSvg('Sosialisasi JDLV Jatim Digital', '15/09/2026'),
    driveUrl: 'https://drive.google.com/drive/folders/1TL5pRoQ7QLeRwD5kYJQeWdK5Yo7c4VQe?usp=sharing',
    categories: ['kolaboratif', 'adaptif', 'kompeten'],
    createdAt: '2026-09-15T09:30:00Z',
  },
  {
    id: 'act-9',
    date: '2026-09-16',
    dateFormatted: 'Rabu, 16 September 2026',
    name: 'Mengikuti senam Bersama di Cabdin Wil. Jember_Kab. Lumajang',
    location: 'Cabang Dinas Pendidikan Wil Jember-Kab Lumajang',
    participants: '• Pengawas\n• Staf Cabdin',
    results:
      'Kegiatan Senam berjalan lancar Bersama dengan pengawas dan pegawai Cabdin Wil. Jember-Kab. Lumajang Bersama dengan SMAN 3 Lumajang',
    photoUrl: createActivityPlaceholderSvg('Senam Bersama SMAN 3 Lumajang', '16/09/2026'),
    driveUrl: '',
    categories: ['kolaboratif', 'harmonis'],
    createdAt: '2026-09-16T07:30:00Z',
  },
  {
    id: 'act-10',
    date: '2026-09-18',
    dateFormatted: 'Jumat, 18 September 2026',
    name: 'Rapat Koordinasi JELAS GO GLOBAL',
    location: 'Zoom Meeting',
    participants: '• Kepala Cabang Dinas Wilayah Jember\n• Kasubag\n• Kasi SMA/SMK\n• Pengawas\n• Kepala Sekolah',
    results: 'Program JELAS GO GLOBAL di wilayah Cabdindik Jember tersosialisasikan dengan baik',
    photoUrl: createActivityPlaceholderSvg('Rakor JELAS GO GLOBAL Jember', '18/09/2026'),
    driveUrl: 'https://drive.google.com/drive/folders/1TL5pRoQ7QLeRwD5kYJQeWdK5Yo7c4VQe?usp=sharing',
    categories: ['kolaboratif', 'adaptif', 'berorientasi_pelayanan'],
    createdAt: '2026-09-18T13:30:00Z',
  },
  {
    id: 'act-11',
    date: '2026-09-21',
    dateFormatted: 'Senin, 21 September 2026',
    name: 'Apel Senin Pagi',
    location: 'Kantor Cabang Dinas Wilayah Jember-Kab. Lumajang',
    participants: '• Pengawas Sekolah\n• Staf Cabdin Wilayah Jember',
    results:
      'Terjadi peningkatan disiplin dan kedisiplinan, membangun kebersamaan dan kekeluargaan antar pegawai, serta menjadi sarana komunikasi efektif untuk penyampaian arahan pimpinan, informasi penting, dan evaluasi kinerja.',
    photoUrl: createActivityPlaceholderSvg('Apel Disiplin Pagi Cabdin', '21/09/2026'),
    driveUrl: 'https://drive.google.com/drive/folders/1TL5pRoQ7QLeRwD5kYJQeWdK5Yo7c4VQe?usp=sharing',
    categories: ['kolaboratif', 'loyal', 'akuntabel'],
    createdAt: '2026-09-21T07:15:00Z',
  },
  {
    id: 'act-12',
    date: '2026-09-21',
    dateFormatted: 'Senin, 21 September 2026',
    name: 'FGD',
    location: 'Kantor Pengawas Cabang Dinas Wilayah Jember-Kab. Lumajang',
    participants: '• Korwas\n• Pengawas Sekolah',
    results:
      'Dapat mengumpulkan wawasan mendalam tentang pendapat, sikap, dan persepsi terkait dengan topik yang sedang dibahas.',
    photoUrl: createActivityPlaceholderSvg('FGD Pengawas Cabdin Lumajang', '21/09/2026'),
    driveUrl: '',
    categories: ['kolaboratif', 'kompeten', 'berorientasi_pelayanan'],
    createdAt: '2026-09-21T10:00:00Z',
  },
  {
    id: 'act-13',
    date: '2026-09-23',
    dateFormatted: 'Rabu, 23 September 2026',
    name: 'Mengikuti senam Bersama di Cabdin Wil. Jember_Kab. Lumajang',
    location: 'Cabang Dinas Pendidikan Wil Jember-Kab Lumajang',
    participants: '• Pengawas\n• Staf Cabdin',
    results:
      'Kegiatan Senam berjalan lancar Bersama dengan pengawas dan pegawai Cabdin Wil. Jember-Kab. Lumajang Bersama dengan SMK WYSN Lumajang',
    photoUrl: createActivityPlaceholderSvg('Senam SMK WYSN Lumajang', '23/09/2026'),
    driveUrl: '',
    categories: ['kolaboratif', 'harmonis'],
    createdAt: '2026-09-23T07:30:00Z',
  },
  {
    id: 'act-14',
    date: '2026-09-28',
    dateFormatted: 'Senin, 28 September 2026',
    name: 'Apel Senin Pagi',
    location: 'Kantor Cabang Dinas Wilayah Jember-Kab. Lumajang',
    participants: '• Pengawas Sekolah\n• Staf Cabdin Wilayah Jember',
    results:
      'Terjadi peningkatan disiplin dan kedisiplinan, membangun kebersamaan dan kekeluargaan antar pegawai, serta menjadi sarana komunikasi efektif untuk penyampaian arahan pimpinan, informasi penting, dan evaluasi kinerja.',
    photoUrl: createActivityPlaceholderSvg('Apel Senin Pagi Akhir Bulan', '28/09/2026'),
    driveUrl: 'https://drive.google.com/drive/folders/1TL5pRoQ7QLeRwD5kYJQeWdK5Yo7c4VQe?usp=sharing',
    categories: ['kolaboratif', 'loyal', 'akuntabel'],
    createdAt: '2026-09-28T07:15:00Z',
  },
  {
    id: 'act-15',
    date: '2026-09-28',
    dateFormatted: 'Senin, 28 September 2026',
    name: 'FGD',
    location: 'Kantor Pengawas Cabang Dinas Wilayah Jember-Kab. Lumajang',
    participants: '• Korwas\n• Pengawas Sekolah',
    results:
      'Dapat mengumpulkan wawasan mendalam tentang pendapat, sikap, dan persepsi terkait dengan topik yang sedang dibahas.',
    photoUrl: createActivityPlaceholderSvg('FGD Evaluasi Program Cabdin', '28/09/2026'),
    driveUrl: '',
    categories: ['kolaboratif', 'kompeten', 'berorientasi_pelayanan'],
    createdAt: '2026-09-28T10:00:00Z',
  },
  {
    id: 'act-16',
    date: '2026-09-30',
    dateFormatted: 'Rabu, 30 September 2026',
    name: 'Mengikuti senam Bersama di Cabdin Wil. Jember_Kab. Lumajang',
    location: 'Cabang Dinas Pendidikan Wil Jember-Kab Lumajang',
    participants: '• Pengawas\n• Staf Cabdin',
    results:
      'Kegiatan Senam berjalan lancar Bersama dengan pengawas dan pegawai Cabdin Wil. Jember-Kab. Lumajang Bersama dengan SMKN 1 Lumajang',
    photoUrl: createActivityPlaceholderSvg('Senam SMKN 1 Lumajang Penutup', '30/09/2026'),
    driveUrl: 'https://drive.google.com/drive/folders/1TL5pRoQ7QLeRwD5kYJQeWdK5Yo7c4VQe?usp=sharing',
    categories: ['kolaboratif', 'harmonis'],
    createdAt: '2026-09-30T07:30:00Z',
  },
];
